# Generated by Django 5.0 on 2024-01-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_contact_options_alter_portfolio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='skill_id',
            field=models.ManyToManyField(to='base.skill', verbose_name='Skills'),
        ),
    ]
