# Generated by Django 5.0 on 2024-01-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_workexperience_skill_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone_number',
        ),
    ]
