# Generated by Django 5.0 on 2024-01-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField()),
                ('image', models.ImageField(upload_to='bookmarks/')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
