# Generated by Django 5.0 on 2024-01-18 16:05

import apps.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0005_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='image',
            field=models.ImageField(upload_to='bookmarks/', validators=[apps.base.models.validate_image_extension], verbose_name='Image'),
        ),
    ]
