# Generated by Django 4.2.4 on 2024-01-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
